baseURL = 'http://portfolio.udhi.net/'
languageCode = 'en_us'
title = 'My Portfolio'
theme = 'hugo-theme-stack'

defaultContentLanguage = 'en'

[params]
  [params.footer]
    since = '2023'
    
  [params.sidebar]
    [params.sidebar.avatar]
      enabled = true
      local = false
      src = 'https://github.com/polyacetal.png'
      
  [params.colorScheme]
    toggle = true
    default = 'auto'

[menu]
  social = [
    { identifier = 'github', name = 'github', url = 'https://github.com/polyacetal', params.icon = 'brand-github'}
  ]
