baseURL = 'http://portfolio.udhi.net/'
languageCode = 'ja_jp'
title = 'My Portfolio'
theme = 'hugo-theme-stack'

defaultContentLanguage = 'jp'

[params]
  [params.sidebar]
    [params.sidebar.avatar]
      enabled = true
      local = true
      src = 'img/avatar.png'
